### ISSUE TITLE
Github profile link isn't correct

### ISSUE THREAD

**Issue by hmert** [aikerim/aikerim.github.io#1]
@aikerim or @aikyerim

https://github.com/aikerim/aikerim.github.io/blob/master/about.md

**Comment by aikerim** [comment]
thanks! [resolved]

**Comment by hmert** [comment]
9a713ae6ddd2882601843b087c8c499167577707

you should use [commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/) to close a issue
